name: DSi-curl-v2
on:
  push:
    branches:
    - master
jobs:
  build-nds:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download custom packages
      run: |
          curl -L https://github.com/cavv-dev/nds-curl/releases/download/curl-7.83.0%2Bwolfssl-5.7.6/nds-wolfssl-5.7.6-2-any.pkg.tar.zst -o nds-wolfssl-5.7.6-2-any.pkg.tar.zst 
          curl -L https://github.com/cavv-dev/nds-curl/releases/download/curl-7.83.0%2Bwolfssl-5.7.6/nds-curl-7.83.0-1-any.pkg.tar.zst -o nds-curl-7.83.0-1-any.pkg.tar.zst  
    - name: Install custom packages
      run: |
            sudo dkp-pacman -U --noconfirm nds-curl-7.83.0-1-any.pkg.tar.zst nds-wolfssl-5.7.6-2-any.pkg.tar.zst
            sudo dkp-pacman -Ql 
    - name: Compile
      run: |
        make -f Makefile-DSi-7
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: dsi-curl
        path: |
          *.nds
    
