name: GBA-curl-v1
on:
  push:
    branches:
    - main
jobs:
  build-3ds:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make -f Makefile-GBA-1
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: GBA-curl
        path: |
          *.elf
          *.gba
