name: GBA-butano-v4
on:
  push:
    branches:
    - master
jobs:
  build-GBA-butano:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install custom packages
      run: |
        sudo dkp-pacman -Ql 
    - name: Clone_Repos
      run: |
        git clone --branch master --depth 1 https://github.com/AntonioND/libugba
        cd libugba
        mkdir build
        cd build
        cmake .. 
        make
        git clone --branch main --depth 1 https://github.com/felixjones/agbabi.git
        cd agbabi
        sudo cmake -S . -B build
        git clone --branch master --depth 1 https://github.com/GValiente/butano.git 
        cd butano
    - name: Compile
      run: |
        make -f Makefile-GBA-butano-3
    - name: Upload
      uses: actions/upload-artifact@v5
      with:
        name: GBA-butano
        path: |
          *.gba
