name: GBA-curl-v1
on:
  push:
    branches:
    - master
jobs:
  build-GBA:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install custom packages
      run: |
            sudo dkp-pacman -Ql 
    - name: Compile
      run: |
        make -f Makefile-GBA-3
    - name: Upload
      uses: actions/upload-artifact@v5
      with:
        name: GBA-curl
        path: |
          *.gba
