name: GBA-butano-v3
on:
  push:
    branches:
    - main
jobs:
  build-GBA-butano:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Clone_Repos
      run: |
        cd .
        mkdir build
        cd build
        git clone --branch main --depth 1 https://github.com/felixjones/agbabi.git /build
        sudo cmake -S . -B build --toolchain=cross/agb.cmake
        sudo cmake --build build
        cd .
        git clone --branch master --depth 1 https://github.com/GValiente/butano.git /butano
    - name: Install custom packages
      run: |
            sudo dkp-pacman -Ql 
    - name: Compile
      run: |
        make -f Makefile-GBA-butano-2
    - name: Upload
      uses: actions/upload-artifact@v5
      with:
        name: GBA-butano
        path: |
          *.gba
