name: GBA-butano-v1
on:
  push:
    branches:
    - master
jobs:
  build-GBA-butano:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install SDL2
      run: |
        mkdir build
        cd build
        git clone --branch master --depth 1 https://github.com/GValiente/butano.git
        cmake sdl
        make
        sudo make install
    - name: Install custom packages
      run: |
            sudo dkp-pacman -Ql 
    - name: Compile
      run: |
        make -f Makefile-GBA-butano
    - name: Upload
      uses: actions/upload-artifact@v5
      with:
        name: GBA-butano
        path: |
          *.gba
